#!/usr/bin/env bun
/**
 * @fileoverview Generate `corpus/ATTRIBUTION.md` from every fixture's `meta.json`, so
 * each openly licensed document in the corpus carries its credit and license in the
 * repository. `--check` exits 1 when the committed file is stale.
 * @module scripts/corpus/attribution
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

interface FixtureMeta {
  attribution: string;
  format: string;
  id: string;
  license: { id: string; url?: string };
  url: string;
}

const CORPUS = 'corpus';
const OUT = join(CORPUS, 'ATTRIBUTION.md');

const metas: FixtureMeta[] = [];
for (const format of readdirSync(CORPUS, { withFileTypes: true })) {
  if (!format.isDirectory()) continue;
  for (const fixture of readdirSync(join(CORPUS, format.name), { withFileTypes: true })) {
    const metaPath = join(CORPUS, format.name, fixture.name, 'meta.json');
    if (fixture.isDirectory() && existsSync(metaPath)) {
      metas.push(JSON.parse(readFileSync(metaPath, 'utf8')) as FixtureMeta);
    }
  }
}
metas.sort((a, b) => a.format.localeCompare(b.format) || a.id.localeCompare(b.id));

const cell = (value: string) =>
  value.replaceAll('\\', '\\\\').replaceAll('|', '\\|').replaceAll('\n', ' ');
const license = (m: FixtureMeta) =>
  m.license.url ? `[${m.license.id}](${m.license.url})` : m.license.id;

const content = [
  '# Corpus attribution',
  '',
  "Generated by `scripts/corpus/attribution.ts` from each fixture's `meta.json` — do not edit by hand.",
  '',
  "Every document under `corpus/` is the work of its authors, redistributed here unmodified under the license listed. This project's Apache-2.0 license does not apply to them.",
  '',
  ...(metas.length === 0
    ? ['No fixtures yet.']
    : [
        '| Fixture | Work | License | Source |',
        '|:---|:---|:---|:---|',
        ...metas.map(
          (m) =>
            `| \`${m.format}/${m.id}\` | ${cell(m.attribution)} | ${license(m)} | <${m.url}> |`,
        ),
      ]),
  '',
].join('\n');

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== content) {
    console.error(`${OUT} is stale. Run: bun run scripts/corpus/attribution.ts`);
    process.exit(1);
  }
  console.log(`${OUT} is in sync (${metas.length} fixtures).`);
} else {
  writeFileSync(OUT, content);
  console.log(`Wrote ${OUT} (${metas.length} fixtures).`);
}
